Repository celestiaorg/celestia-specs, pull requests merged in 2020-06, with the labels that each got.

#32 Add state representation
  proto/types.proto
  rationale/distributing_rewards.md
  specs/consensus.md
  specs/data_structures.md
Labels: documentation, enhancement

#39 Fix namespace ID type
  specs/consensus.md
Labels: bug, documentation

#40 Change figure URLs to VuePress compatible relative URLs
  specs/data_structures.md
Labels: bug, documentation

#38 Remove protobuf use for core data structures
  README.md
  proto/types.proto
  specs/data_structures.md
Labels: bug, documentation

#37 Change protobuf timestamps to TAI64 timestamps
  specs/data_structures.md
Labels: documentation, enhancement

#36 Add message layout rationale
  rationale/message_block_layout.md
  specs/data_structures.md
Labels: documentation, enhancement

#43 Bump github-action-markdown-link-check from 0.6.0 to 1.0.3.
  .github/workflows/action.yml
Labels: github actions

#42 Add transaction types
  specs/consensus.md
  specs/data_structures.md
Labels: documentation, enhancement

#44 Add type aliases
  specs/consensus.md
  specs/data_structures.md
Labels: documentation, enhancement
