Repository celestiaorg/celestia-specs, pull requests merged in 2020-09, with the labels that each got.

#61 Add release drafter CI.
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: ci

#70 Reduce namespace ID size to 8 bytes, from 32
  specs/consensus.md
  specs/data_structures.md
Labels: bug

#66 Add erasure code fraud proof specification
  specs/data_structures.md
Labels: enhancement

#71 Clarify how shares are split
  specs/data_structures.md
  specs/figures/share.dot
  specs/figures/share.svg
Labels: bug

#74 Minor: clean up old ToC for block proposer page
  specs/block_proposer.md
Labels: bug, documentation
