Repository celestiaorg/celestia-specs, pull requests merged in 2021-03, with the labels that each got.

#135 Minor fixes
  specs/figures/block_data_structures.dot
  specs/proto/consensus.proto
Labels: bug, documentation

#138 Make Actions run on fork PRs
  .github/workflows/markdown_link_checker.yml
Labels: ci

#141 Make GitHub action run on push or PR update, exclusive
  .github/workflows/markdown_link_checker.yml
Labels: ci

#136 data structures:update vote
  specs/data_structures.md
Labels: consensus

#144 Simplify DA header to commit to full row and column roots
  specs/consensus.md
  specs/data_structures.md
Labels: enhancement

#146 Erasure-code namespace ID
  specs/data_structures.md
  specs/figures/share.dot
  specs/figures/share.svg
Labels: bug

#150 Prepend length to messages too
  specs/data_structures.md
Labels: consensus, enhancement

#149 Fix non-interactive empty share message NID requirement
  specs/data_structures.md
Labels: bug, consensus

#151 Clarify minimum square size = 1
  specs/data_structures.md
Labels: documentation
